### Регистрация нового юзера
POST http://localhost:8081/auth/reg
Content-Type: application/json

{
  "login": "login18",
  "password": "password4"
}

### Аутентификация юзера
POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "login": "login18",
  "password": "password4",
  "info": {
    "fingerprint": "d",
    "version": "12"
  }
}

### Проверка access token
POST http://localhost:8081/auth/check
Content-Type: application/json

{
  "accessToken": "*.*.*",
  "checkBlock": "false"
}

### Проверка refresh token
POST http://localhost:8081/auth/refresh
Content-Type: application/json

{
  "refreshToken": "*.*.*",
  "info": {
    "fingerprint": "d",
    "version": "_"
  }
}

### Блокировка сесии по рефреш токену
POST http://localhost:8081/auth/block
Content-Type: application/json

{
  "sessionId": "*"
}

### Создание share_auth токена для внешней аутентификации
POST http://localhost:8081/auth/share
Content-Type: application/json

{
  "refreshToken": "*.*.*"
}

### Блокировка сесии по рефреш токену
POST http://localhost:8081/auth/share_login
Content-Type: application/json

{
  "refreshToken": "*.*.*",
  "info": {
    "fingerprint": "*"
  }
}

### Блокировка access токена
POST http://localhost:8081/auth/sessions
Content-Type: application/json

{
  "accessToken": "*.*.*"
}

### Test
GET http://localhost:8081/auth/test

