### Регистрация нового юзера
POST http://localhost:8081/auth/reg
Content-Type: application/json

{
  "login": "login18",
  "password": "password4"
}

### Аутентификация юзера
POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "login": "login18",
  "password": "password4",
  "info": {
    "fingerprint": "d",
    "version": "12"
  }
}

### Проверка access token
POST http://localhost:8081/auth/check
Content-Type: application/json

{
  "accessToken": "*.*.*",
  "checkBlock": "true"
}

### Проверка refresh token
POST http://localhost:8081/auth/refresh
Content-Type: application/json

{
  "refreshToken": "*.*.*",
  "info": {
    "fingerprint": "*",
    "version": "_"
  }
}

### Блокировка сесии по рефреш токену
POST http://localhost:8081/auth/block
Content-Type: application/json

{
  "refreshToken": "*.*.*"
}

### Создание share_auth токена для внешней аутентификации
POST http://localhost:8081/auth/share
Content-Type: application/json

{
  "refreshToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsb2dpbjE4IiwidHR5cGUiOiJyZWZyZXNoIiwiZXhwIjoxNjYyMTAzNzY5LCJqdGkiOiIyOTEyZjU4YzgyZDI0NWU4YjMyOTQ1ZTg0OWMyMzA2ZSJ9.6AbCc3u1XfvSiKPQGGrFzOXY7HDqL9P-H0jje4CPbsA"
}

### Блокировка сесии по рефреш токену
POST http://localhost:8081/auth/share_login
Content-Type: application/json

{
  "authShareToken": "*",
  "info": {
    "fingerprint": "*"
  }
}

### Блокировка access токена
POST http://localhost:8081/auth/block_access
Content-Type: application/json

{
  "token": "*.*.*"
}


